# Numpy Reference Guide
*A guide of useful methods which I've discovered over time, and a presentation of some standard ones; compiled by Andrea Walker February 2021.*

# Basics

## Creating Arrays

### np.array(), .ones(), .zeros(), .empty()

In [1]:
'''
np.array([3,6,9]) # creating a general array from a list
np.ones()         # creating an array of ones; pass an integer(length of 1D array) or tuple (shape of N-D array)
np.zeros()        # same syntax as ones
np.empty()        # same syntax as ones      
'''
import numpy as np

### numpy.full(shape, fill_value, dtype=None, order='C', *, like=None)
> Return a new array of given shape and type, filled with fill_value.\
> https://numpy.org/doc/stable/reference/generated/numpy.full.html

#### *This is useful for creating an array of booleans*

In [2]:
np.full((3,4),True)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

## Generating Series of numbers
A general comment on the two main numpy functions generating series of numbers : arange and linspace (if this is too big of a block of text, jump down to the tl;dr).

### np.linspace(start, stop, num=50)
>Linspace returns an array of  num  elements evenly spaced over the closed interval [start, stop].
 More verbosely, linspace requires two arguments (start and stop), and returns an array of length num  (default is 50) containing evenly spaced numbers beginning with start,  up to and including stop.
 > https://numpy.org/doc/stable/reference/generated/numpy.linspace.html

### np.arange([start, ]stop, [step, ])
>Arange returns an array of of evenly spaced elements over the half-open interval [start,stop). The number of elements is determined by step, which defaults to 1. 
More verbosely, arange requires one argument (stop), and returns an array containing evenly spaced numbers beginning with start (defaults to 0), at intervals of step (default of 1), up to but not including stop.
> https://numpy.org/doc/stable/reference/generated/numpy.arange.html

TL;DR : If you want to create an array of evenly spaced numbers, use linspace if you care about the number of points  in the array. Otherwise, use arange  if you are interested in the distance between the points in the array.

In [3]:
lnspace = np.linspace(1,10,20)
arng = np.arange(1,10,1.5)
print(lnspace,'\n',arng)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ] 
 [1.  2.5 4.  5.5 7.  8.5]


## Maximum and Minimum values, indices

**Note: for N-D arrays (N>1), all of the following flatten the input array unless an axis is specified.**

### numpy.amax(a, axis=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)
>Return the maximum of an array or maximum along an axis. \
>https://numpy.org/doc/stable/reference/generated/numpy.amax.html
    
### numpy.argmax(a, axis=None, out=None)
>Returns the indices of the maximum values along an axis. \
> https://numpy.org/doc/stable/reference/generated/numpy.argmax.html
    
### numpy.amin(a, axis=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)
>Return the minimum of an array or minimum along an axis.\
>https://numpy.org/doc/stable/reference/generated/numpy.amin.html
    
### numpy.argmin(a, axis=None, out=None)
>Returns the indices of the minimum values along an axis. \
>https://numpy.org/doc/stable/reference/generated/numpy.argmin.html

## Returning a subset of an array

### Based on a condition 

#### numpy.compress(condition, a, axis=None, out=None)[source]
> Return selected slices of an array along given axis.
> When working along a given axis, a slice along that axis is returned in output for each index where condition evaluates to True. When working on a 1-D array, compress is equivalent to extract.
> https://numpy.org/doc/stable/reference/generated/numpy.compress.html

In [4]:
#(one example: mask)
mask = np.full(5,True)
mask[2]=False
arr = np.arange(5)
new_arr = np.compress(mask,arr)
print("Mask: {} \n Original array: {} \n Masked array: {}".format(mask,arr,new_arr))

Mask: [ True  True False  True  True] 
 Original array: [0 1 2 3 4] 
 Masked array: [0 1 3 4]


In [5]:
#compress based on condition
arr = np.arange(10)
new_arr = np.compress(arr>5,arr)
print(arr,'\n',new_arr)

[0 1 2 3 4 5 6 7 8 9] 
 [6 7 8 9]


### numpy.take(a, indices, axis=None, out=None, mode='raise')[source]
>Take elements from an array along an axis. \
>When axis is not None, this function does the same thing as “fancy” indexing (indexing arrays using arrays); however, it can be easier to use if you need elements along a given axis. A call such as np.take(arr, indices, axis=3) is equivalent to arr[:,:,:,indices,...]. \
> Explained without fancy indexing, this is equivalent to the following use of ndindex, which sets each of ii, jj, and kk to a tuple of indices:
> https://numpy.org/doc/stable/reference/generated/numpy.take.html

In [6]:
ind = np.arange(0,20,step=2)
x_sq = np.array([2**x for x in range(25)])

print(ind)
print(x_sq)
print(np.take(x_sq,ind))

[ 0  2  4  6  8 10 12 14 16 18]
[       1        2        4        8       16       32       64      128
      256      512     1024     2048     4096     8192    16384    32768
    65536   131072   262144   524288  1048576  2097152  4194304  8388608
 16777216]
[     1      4     16     64    256   1024   4096  16384  65536 262144]


## Conditionally populate

### numpy.where(condition[, x, y])
>Return elements chosen from x or y depending on condition.\
>https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [7]:
x = np.random.normal(size=10)
x_relu = np.where(x>0,x,0)
print(x,'\n',x_relu)

[-0.23138199  0.83137214 -0.52872266  0.85988448  1.05366627 -1.50077147
 -0.02075735 -2.16167276  1.45940071  0.13812204] 
 [0.         0.83137214 0.         0.85988448 1.05366627 0.
 0.         0.         1.45940071 0.13812204]


## Comparing two arrays

### numpy.isclose(a, b, rtol=1e-05, atol=1e-08, equal_nan=False)
>Returns a boolean array where two arrays are element-wise equal within a tolerance. \
> The tolerance values are positive, typically very small numbers. The relative difference (rtol * abs(b)) and the absolute difference atol are added together to compare against the absolute difference between a and b.
> https://numpy.org/doc/stable/reference/generated/numpy.isclose.html

In [8]:
arr1 = np.ones(5)
arr2 = np.ones(5)
close = np.isclose(arr1,arr2,atol=1e-7)
print(close)

[ True  True  True  True  True]


In [9]:
arr1 = 0.5*np.ones(5)
arr2 = np.ones(5)
print(np.isclose(arr1,arr2,atol=0.6))
print(np.isclose(arr1,arr2,atol=0.4))

[ True  True  True  True  True]
[False False False False False]


## Boolean Evaluation

### numpy.all(a, axis=None, out=None, keepdims=<no value>, *, where=<no value>)
>Test whether all array elements along a given axis evaluate to True.\
>https://numpy.org/doc/stable/reference/generated/numpy.all.html

In [10]:
temp = [True,True,False]
print(np.all(temp))
print(np.all(temp[0:2]))

False
True


### numpy.any(a, axis=None, out=None, keepdims=<no value>, *, where=<no value>)
>Test whether any array element along a given axis evaluates to True.
> Returns single boolean unless axis is not None
>https://numpy.org/doc/stable/reference/generated/numpy.any.html

In [11]:
temp = [False,False,True]
print(np.any(temp))
print(np.any(temp[0:2]))

True
False


# Appendix: non-Numpy tips and tricks:

### String number formatting: 
https://mkaz.blog/code/python-string-format-cookbook/